name: now
description: >-
  A minimalist DateTime library for validating, parsing, manipulating and formatting times.
version: 1.0.1
repository: https://github.com/odroe/now

environment:
  sdk: "<4.0.0"

dev_dependencies:
  lints: ">=3.0.0 <7.0.0"
  test: ^1.21.0
